version: '3.8'

services:
  # Redis for L2 caching
  redis:
    image: redis:7-alpine
    container_name: options_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    networks:
      - options_network

  # FastAPI backend (optional - for full stack deployment)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: options_api
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - PHASE4_WS_INTERVAL_SECONDS=30
      - LOG_LEVEL=INFO
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - options_network
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  options_network:
    driver: bridge

